all:

run:
	sh run.sh

ls:
	ls -l

clean:
	rm -rf .* *~

cleanData:
	rm -rf \
		*.out \
		*.test \
		*.train \
		*.model \
		*.candidates \
		*.predict \
		*.exposure \
		*.clicked \
		*.augment \
		*.recommend \
		*.passed

